version: '3.7'

services:
  night-owl-api:
    container_name: backend
    image: gchavirajr/night-owl
    command: nodemon server.js
    working_dir: /opt/project3
    ports: 
      - "3001:3001"
    volumes:
      - .:/opt/project3
  redis: 
    image: "redis:5.0.3-stretch"
  mongo: 
    image: "mongo:3.6.11-stretch"

    night-owl:
      container_name: frontend
      image: gchavirajr/night-owl
      command: yarn start
      working_dir: /opt/project/client
      ports:
        - "3000:3000"

