version: '3.7'

services:
  # Backend API
  project3:
    container_name: backend
    build: ./
    command: yarn start
    working_dir: /Users/guadalupechavira/git/project3/project3
    environment: 
      MONGOOSE_URI: MONGODB_URI
      REDIS_URI: redis://redis:6379
    ports: 
      - "3000:3000"
    volumes: 
      - ./:Users/guadalupechavira/git/project3/project3

   # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # mLab
  mongo:
    environment: 
      MONGO_USER: 
      MONGO_PASSWORD: 
      MONGO_URL: MONGODB_URI
      MONGO_DB: project3
      MONGO_HOST: mongodb
    container_name: mongodb
    build: ./mongodb
    ports:
       - "5432:5432"